//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WPFMovieTheatre.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class employee
    {
        public int employeeid { get; set; }
        public string employeename { get; set; }
        public string employeeemail { get; set; }
        public string employeeusername { get; set; }
        public string employeepassword { get; set; }
        public string employeesurname { get; set; }
    
        public virtual admin admin { get; set; }
        public virtual ticketseller ticketseller { get; set; }
        public virtual waiter waiter { get; set; }
    }
}
