//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WPFMovieTheatre.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class NewBioskopEntities : DbContext
    {
        public NewBioskopEntities()
            : base("name=NewBioskopEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<admin> admins { get; set; }
        public virtual DbSet<bar> bars { get; set; }
        public virtual DbSet<bill> bills { get; set; }
        public virtual DbSet<drink> drinks { get; set; }
        public virtual DbSet<employee> employees { get; set; }
        public virtual DbSet<movie> movies { get; set; }
        public virtual DbSet<projectionroom> projectionrooms { get; set; }
        public virtual DbSet<projection> projections { get; set; }
        public virtual DbSet<seat> seats { get; set; }
        public virtual DbSet<snack> snacks { get; set; }
        public virtual DbSet<Table> Tables { get; set; }
        public virtual DbSet<ticket> tickets { get; set; }
        public virtual DbSet<ticketseller> ticketsellers { get; set; }
        public virtual DbSet<waiter> waiters { get; set; }
    }
}
