//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WPFMovieTheatre.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class projection
    {
        public int projectionid { get; set; }
        public int projectionroom_prjroomid { get; set; }
        public int admin_employeeid { get; set; }
        public int movie_movieid { get; set; }
    
        public virtual admin admin { get; set; }
        public virtual movie movie { get; set; }
        public virtual projectionroom projectionroom { get; set; }
    }
}
