//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WPFMovieTheatre.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class snack
    {
        public int snackid { get; set; }
        public string snackname { get; set; }
        public Nullable<long> snackprice { get; set; }
        public int ticketseller_employeeid { get; set; }
    
        public virtual ticketseller ticketseller { get; set; }
    }
}
