//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WPFMovieTheatre.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ticket
    {
        public int ticketid { get; set; }
        public Nullable<long> ticketprice { get; set; }
        public string ticketmoviename { get; set; }
        public string ticketseatnumber { get; set; }
        public Nullable<System.DateTime> ticketdatetime { get; set; }
        public int ticketseller_employeeid { get; set; }
        public int projectionroom_prjroomid { get; set; }
    
        public virtual projectionroom projectionroom { get; set; }
        public virtual ticketseller ticketseller { get; set; }
    }
}
